posts/urls.py
from django.urls import path
from . import views
from project_colab import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "posts"

urlpatterns = [
    path('home/',views.home,name='home'),
    path('delete-comment/<int:post_id>/',views.delete_post,name='delete_post'),
    path('delete-comment/<int:post_id>-<int:comment_id>/',views.delete_comment,name='delete_comment'),
    path('like/<int:post_id>',views.like,name='like'),
    path('dislike/<int:post_id>',views.dislike,name='dislike'),
    path('post_edit/<int:post_id>',views.editpost,name='editpost'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

project_colab/urls.py
from django.contrib import admin
from django.urls import path,include
from reg_sign_in_out import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


urlpatterns = [
    path('',views.index,name="index"),
    path('',include('reg_sign_in_out.urls'),name="reg_sign_in_out"),
    path('',include('networking.urls'),name="networking"),
    path('',include('posts.urls'),name="posts"),
    path('',include('profilepage.urls'),name="profilepage"),
    path('',include('project_management.urls'),name="project_management"),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    path('friendship/', include('friendship.urls'),name='friendship'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'),name='reset_password'),
    path('password-reset/sent/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',success_url = reverse_lazy('reg_sign_in_out:user_login')),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html',),name='password_reset_complete'),

]

posts/models.py
from django.db import models
from reg_sign_in_out.models import User

class Posts(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    time = models.DateTimeField(auto_now_add=True)
    post_text = models.CharField(max_length=1024)
    post_pic = models.ImageField(upload_to='post_pic',blank=True)
    
    def __str__(self):
        return self.post_text
    
class Comment(models.Model):
    post = models.ForeignKey(Posts,on_delete=models.CASCADE,)
    userid = models.ForeignKey(User,on_delete=models.CASCADE,default='')
    comment = models.CharField(max_length=256)
    time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return '{}-{}'.format(self.post.id,self.userid)
    
class Like(models.Model):
    post = models.ForeignKey(Posts,on_delete=models.CASCADE,)
    liked_by = models.ForeignKey(User,on_delete=models.CASCADE,)

    def __str__(self):
        return self.post.post_text
    


# class SubComment(models.Model):
#     post = models.ForeignKey(Posts,on_delete=models.CASCADE,)
#     userid = models.ForeignKey(User,on_delete=models.CASCADE,default='')
#     comment = models.CharField(max_length=256)
#     time = models.DateTimeField(auto_now_add=True)
#     commentx = models.ForeignKey(Comment,on_delete=models.CASCADE)
    
#     def __str__(self):
#         return '{}-{}'.format(self.post,self.userid)

posts/forms.py
from django import forms
from posts.models import *

class PostsForm(forms.ModelForm):

    class Meta:
        model = Posts
        fields = ('post_text','post_pic')

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('comment',)

posts/views.py
from django.shortcuts import render
from posts.models import *
from . import forms 
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from posts.models import Like
from friendship.models import Friend
from django.db.models import Q 

@login_required
def home(request):
    p = Friend.objects.friends(user=User.objects.get(username=request.user.username))
    post_list = Posts.objects.filter(Q(user__in=p)|Q(user=request.user)).order_by('-time')
    page = request.GET.get('page', 1)

    paginator = Paginator(post_list, 5)

    try:
        postx = paginator.page(page)
    except PageNotAnInteger:
        postx = paginator.page(1)
    except EmptyPage:
        postx = paginator.page(paginator.num_pages)
  

    post_creation = forms.PostsForm()
    if request.method == "POST":
        post_creation = forms.PostsForm(request.POST,request.FILES)
        
        if post_creation.is_valid(): 
            entry = post_creation.save(commit=False)
            entry.user = request.user         
            entry.save()
            return HttpResponseRedirect(reverse('posts:home'))
    

    try:
        comment_field = forms.CommentForm()
        if request.method == "POST":
            comment_field = forms.CommentForm(request.POST)
            
            if comment_field.is_valid():
                comment_new = comment_field.save(commit=False)
                post_id = int(list(request.POST)[2])
                comment_new.post = get_object_or_404(Posts,pk=post_id)
                comment_new.userid = get_object_or_404(User,username=request.user.username)
                comment_new.save()

                return HttpResponseRedirect(reverse('posts:home'))
    except:
        pass
        
    return render(request,"posts/index.html",context={"postx":postx,
                            "user":post_creation,
                          "comment_field":comment_field,},
                          )


@login_required
def delete_post(request,post_id):
    post=Posts.objects.get(id=post_id)
    post.delete()
    return HttpResponseRedirect(reverse('posts:home')) 

@login_required
def delete_comment(request,comment_id,post_id):
    comments = Comment.objects.filter(post=Posts.objects.get(id=post_id))
    comments.filter(id=comment_id).delete()
    return HttpResponseRedirect(reverse('posts:home')) 

@login_required
def like(request,post_id):
    
    post=Posts.objects.get(id=post_id)
    like_obj = Like.objects.get_or_create(post=post,liked_by=request.user)[0]
    like_obj.save()
    return HttpResponseRedirect(reverse('posts:home')) 

@login_required
def dislike(request,post_id):

    post=Posts.objects.get(id=post_id)
    Like.objects.get(post=post,liked_by=request.user).delete()
    return HttpResponseRedirect(reverse('posts:home')) 

@login_required
def editpost(request,post_id):
    post=Posts.objects.get(id=post_id)
    if request.method == "POST":    
        post.post_text = request.POST.get('post_text')
        post.save()
        return HttpResponseRedirect(reverse('posts:home')) 

    return render(request,"posts/editpost.html",context={
                            "post_text":post.post_text,
                            },) 



#Alternative for form
        # name = request.POST.get('name')
        # time = timezone.now()
        # post_text = request.POST.get('post_text')

        # temp = Posts(name=name,time=time,post_text=post_text)
        # temp.save()

templates/posts/editpost.html
{% extends "base.html" %}
{% block body_block %}
{% load static %}
{% block head_block %}
<link rel="stylesheet" type="text/css" href="{% static 'posts/post.css'%}">
{% endblock head_block %}

<form method="post">
    {% csrf_token %}
    <label for="post_text">Post Text:</label>
    <input type="text" id="post_text" name="post_text" value="{{post_text}}"><br><br>
    <input type="submit" value="Submit">
</form>
{% endblock %}

templates/posts/index.html
{% extends "base.html" %}
{% block body_block %}
{% load static %}
{% block head_block %}
<link rel="stylesheet" type="text/css" href="{% static 'posts/post.css'%}">
{% endblock head_block %}

{% load custom_tags %}

<div class="container">
    <div class="skew">
        <h1 >Posts</h1>    
    </div>
    <form enctype="multipart/form-data" method="post">
        {%csrf_token%}
        {{user.as_p}}
        <input type="submit" value="Submit">
    </form>

    <div class='infinite-container'>
    {% for x in postx %}
    <div class="bg infinite-item">
        <h2 class="name ">{{x.user.first_name}} {{x.user.last_name}} </h2>
         <h3>{{x.time}} </h3>
        <div class="center">
            {% if x.post_pic %}           
            <img src="{{x.post_pic.url}}" alt="img">
            <h2 class="post"> {{x.post_text}}</h2>       
        {% else %}
            
            <h2 class="post"> {{x.post_text}}</h2> 
        {% endif %}
        


        {% if x.like_set|match:request.user == "False"%}
            <a href="{% url 'posts:like' x.id%}">Like</a>
            
        {% else %}         
            <a href="{% url 'posts:dislike' x.id%}">Dislike</a> 
        {% endif %}

        <br> Like Counter : {{x.like_set.count}}

        {% if x.user.username == request.user.username %}
            <a href="{% url 'posts:delete_post' x.id%}" class="btn-del">Delete Post</a><br>
            <a href="{% url 'posts:editpost' x.id%}">Edit Post</a> 

            {% endif %}

        {% for c in x.comment_set.all  %}
            {{c.comment}}
            {% if c.userid.username == request.user.username or x.user.username == request.user.username %}
                <a href="{% url 'posts:delete_comment' x.id c.id %}" class="btn-comment">Delete Comment</a>
            {% endif %}
            
            <br>
        {% endfor %}
        
        <form action="{% url 'posts:home'%}" method="post">
        {{comment_field.as_p}}
        {%csrf_token%}
        <input type="submit" value="Submit" name="{{x.pk}}" id="{{x.pk}}" class="btn-submit">
        </form>
        </div>
      
    </div>
     
        <br><br>
     
    {% endfor %}
    </div>
    <div class="d-flex d-none position-fixed" style="top:35vh;left:46vw" hidden>
        <button class="btn btn-primary loading">
            <span class="spinner-border spinner-border-sm"></span>
            Please wait...
        </button>
    </div>
    {% if postx.has_next %}
    <a class="infinite-more-link" href="?page={{ postx.next_page_number }}">More</a>
    {% endif %}
    <div class="loading" style="display: none;">
        Loading...
    </div>
  
</div>



<!-- like list -->
<!-- {% for y in x.like_set.all %}
<h1>{{y.liked_by.username}}</h1> <br>
{% endfor %} -->

<script src="/static/js/jquery-3.5.1.js" ></script>
<script src="/static/js/jquery.waypoints.js"></script>
<script src="/static/js/infinite.js"></script>

<script>
    $('.loading').hide();
    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],

        offset: 'bottom-in-view',

        onBeforePageLoad: function () {
            $('.loading').show();
        },
        onAfterPageLoad: function () {
            $('.loading').hide();
        }

    });
    
</script>
{% endblock %}