posts/urls.py
from django.urls import path
from . import views
from project_colab import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "posts"

urlpatterns = [
    path('home/',views.home,name='home'),
    path('delete-comment/<int:post_id>/',views.delete_post,name='delete_post'),
    path('delete-comment/<int:post_id>-<int:comment_id>/',views.delete_comment,name='delete_comment'),
    path('like/<int:post_id>',views.like,name='like'),
    path('dislike/<int:post_id>',views.dislike,name='dislike'),
    path('post_edit/<int:post_id>',views.editpost,name='editpost'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

profilepage/urls.py
from django.urls import path
from . import views

app_name = "profilepage"

urlpatterns = [
    path('profilepage/',views.profilepage,name='profilepage'),
    path('<operation>-<current_user>-<other_user>/',views.friendship_operation,name='friendship_operation'),
    path('project/<operation>-<username>-<project_id>/',views.projectmember,name='projectmember'),
    path('update_info/',views.changeprofileinfo,name='changeprofileinfo'),
]

project_colab/urls.py
from django.contrib import admin
from django.urls import path,include
from reg_sign_in_out import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


urlpatterns = [
    path('',views.index,name="index"),
    path('',include('reg_sign_in_out.urls'),name="reg_sign_in_out"),
    path('',include('networking.urls'),name="networking"),
    path('',include('posts.urls'),name="posts"),
    path('',include('profilepage.urls'),name="profilepage"),
    path('',include('project_management.urls'),name="project_management"),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    path('friendship/', include('friendship.urls'),name='friendship'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'),name='reset_password'),
    path('password-reset/sent/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',success_url = reverse_lazy('reg_sign_in_out:user_login')),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html',),name='password_reset_complete'),

]

reg_sign_in_out/urls.py
from django.urls import path
from . import views

app_name = "reg_sign_in_out"

urlpatterns = [
    path('user_login/',views.user_login,name='user_login'),
    path('registration/',views.registration,name="registration"),
    path('payment/',views.payment,name="payment"),

]

profilepage/models.py
from django.db import models

profilepage/forms.py
from django import forms
from django.contrib.auth.models import User
from reg_sign_in_out.models import Registration

class UserChangeForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name','last_name','email')

class RegistrationChangeForm(forms.ModelForm):

    class Meta:
        model = Registration
        fields = ('profile_pic',)

profilepage/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from posts.models import *
from friendship.models import FriendshipRequest,Block,Follow,Friend
from django.http import HttpResponseRedirect
from django.urls import reverse
from project_management.models import *
from . import forms
from reg_sign_in_out.models import Registration
from django.contrib.auth.models import User

@login_required
def profilepage(request):

    posts_obj = Posts.objects.filter(user=request.user)
    comment_obj = Comment.objects.filter(userid=request.user)
    friend_reqs = Friend.objects.requests(user=request.user)
    friend_list = Friend.objects.friends(request.user)
    project_req_list = ProjectInductionRequest.objects.filter(project__team_lead=request.user)
    paid_bool = Registration.objects.get(user=request.user).paid
    return render(request,"profilepage/profilepage.html",{"user":request.user,
                                                          "posts_obj":posts_obj,
                                                          "comment_obj":comment_obj,
                                                          "req_list":friend_reqs,
                                                          "friend_list":friend_list,
                                                          "project_req_list":project_req_list,
                                                          "paid_bool":paid_bool})
@login_required
def friendship_operation(request,operation,current_user,other_user):

    u1 = User.objects.get(username=current_user)
    u2 = User.objects.get(username=other_user)

    friend_request = FriendshipRequest.objects.get(to_user=u1,from_user=u2)

    if operation == "Reject":
        print(operation,"\n"*3)
        friend_request.delete()

    if operation == "Accept":
        friend_request.accept()

    if operation == "Remove":
        Friend.objects.remove_friend(u1, u2)

    return HttpResponseRedirect(reverse('profilepage:profilepage')) 

def projectmember(request,operation,username,project_id):

    u = User.objects.get(username=username)

    if operation=="Accept":
        ProjectMembers.func.add_member(request.user,u,project_id)

    if operation=="Reject":
        ProjectMembers.func.reject_member(u,project_id)

    if operation=="Remove":
        ProjectMembers.func.remove_member(u,project_id)

    return HttpResponseRedirect(reverse('profilepage:profilepage')) 


def changeprofileinfo(request):
 
    if request.method == "POST":
        form = forms.UserChangeForm(request.POST)
        profileform = forms.RegistrationChangeForm(request.POST,request.FILES)
        print(request.POST)
        if form.is_valid() and profileform.is_valid():
            
            # user = form.save(commit=False)
            # user = request.user
            # user.save()
            cuser = User.objects.get(username=request.user.username)

            if len(request.POST['first_name'])!=0:
                cuser.first_name = request.POST['first_name']
            if len(request.POST['last_name'])!=0:
                cuser.last_name = request.POST['last_name']
            if len(request.POST['email'])!=0:
                cuser.email = request.POST['email']
            cuser.save()

            Registration.objects.get(user=request.user).delete()
            profile = profileform.save(commit=False)
            profile.user = request.user
            
            profile.save()

            return HttpResponseRedirect(reverse('profilepage:profilepage'))

        else:

            print(form.errors,profileform.errors)
            
            return render(request,"profilepage/change.html",{"tried":"True",
                                                   "profile_form":profileform,
                                                   "user_form":form,
                                                   })
            

    else:
        form = forms.UserChangeForm()
        profileform = forms.RegistrationChangeForm()

    return render(request,"profilepage/change.html",{
                                                   "profile_form":profileform,
                                                   "user_form":form,
                                                   })

templates/profilepage/change.html
{% extends "base.html" %}
{% load static %}
{% block head_block %}
<link rel="stylesheet" type="text/css" href="{% static 'reg_sign_in_out/reg.css'%}">
{% endblock head_block %}
{% block body_block %}
<div class="bg">
    <h3 id="fill">FILL</h3>
    <div id="form">
        <div class="float_left">
            <form enctype="multipart/form-data" method="post">
                <div class="block">
                    {% csrf_token %}
                </div>                
                {{user_form.as_p}}
                {{profile_form.as_p}}
                {% csrf_token %}
                <input type="submit" value="Submit" id="sub">
            </form>
        </div>
    </div>

</div>
{% endblock %}

templates/profilepage/profilepage.html
{% extends "base.html" %}

{% load static %}
{% block head_block %}
<link rel="stylesheet" type="text/css" href="{% static 'profilepage/profile.css' %}">
{% endblock head_block %}




{% block body_block %}
<header>
  
</header>
<div class="center">
  <img src="{{user.registration.profile_pic.url}}" alt="img" id="profileimg" onerror="this.onerror=null; this.src='/media/profile_pic/no_pro_pic.jpg'">

  <h1 id="username">{{user.first_name}} {{user.last_name}}</h1>{{user.registration.url}}{{user.username}}
<br><br>

{% if paid_bool == False %}
  <button class="btn btn-outline-success"><a href="{% url 'reg_sign_in_out:payment' %}">Become Member</a></button>
{% else %}
<h3>Already A Member</h3>
{% endif %}
<button class="btn btn-outline-success"><a href="{% url 'profilepage:changeprofileinfo' %}">Update Information</a></button>
{% for req in req_list %}
  {{req.from_user.username}}
  <a href="{% url 'profilepage:friendship_operation' 'Accept' request.user req.from_user.username %}" class="btn-del">Accept</a><br>
  <a href="{% url 'profilepage:friendship_operation' 'Reject' request.user req.from_user.username %}" class="btn-del">Reject</a><br>
  {% endfor %}

{% for friend in friend_list %}
  {{friend.from}}
{% endfor %}

{% for post in posts_obj%}
    {% if post.post_pic %}
        <img src="{{post.post_pic.url}}" alt="img">
    {% endif %}
    {{post.post_text}}
{% endfor %}
<br>
{% for comment in comment_obj %}
 Comment Post: {{comment.post.post_text}}  <br>
  {% if comment.post.post_pic %}
  <img src="{{comment.post.post_pic.url}}" alt="img">
  {% endif %}
{% endfor %}

{% for req in project_req_list %}
  {{req.from_user.username}}
  <a href="{% url 'profilepage:projectmember' 'Accept' req.user.username req.project.id %}" class="btn-del">Accept</a><br>
  <a href="{% url 'profilepage:projectmember' 'Reject' req.user.username req.project.id %}" class="btn-del">Reject</a><br>
  {% endfor %}



</div>

    
{% endblock %}


<!-- important: https://pypi.org/project/django-friendship/ -->