networking/urls.py
from django.urls import path
from . import views
from project_colab import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "networking"

urlpatterns = [
    path('search/',views.search,name='search'),
    path('profile/<username>/',views.profile,name='profile'),
    path('friend/<operation>-<usernameone>-<usernametwo>/',views.friend,name='friend'),
    path('project/projectid<project_id>/',views.project_view,name='project_view'),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

posts/urls.py
from django.urls import path
from . import views
from project_colab import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "posts"

urlpatterns = [
    path('home/',views.home,name='home'),
    path('delete-comment/<int:post_id>/',views.delete_post,name='delete_post'),
    path('delete-comment/<int:post_id>-<int:comment_id>/',views.delete_comment,name='delete_comment'),
    path('like/<int:post_id>',views.like,name='like'),
    path('dislike/<int:post_id>',views.dislike,name='dislike'),
    path('post_edit/<int:post_id>',views.editpost,name='editpost'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

profilepage/urls.py
from django.urls import path
from . import views

app_name = "profilepage"

urlpatterns = [
    path('profilepage/',views.profilepage,name='profilepage'),
    path('<operation>-<current_user>-<other_user>/',views.friendship_operation,name='friendship_operation'),
    path('project/<operation>-<username>-<project_id>/',views.projectmember,name='projectmember'),
    path('update_info/',views.changeprofileinfo,name='changeprofileinfo'),
]

project_colab/urls.py
from django.contrib import admin
from django.urls import path,include
from reg_sign_in_out import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


urlpatterns = [
    path('',views.index,name="index"),
    path('',include('reg_sign_in_out.urls'),name="reg_sign_in_out"),
    path('',include('networking.urls'),name="networking"),
    path('',include('posts.urls'),name="posts"),
    path('',include('profilepage.urls'),name="profilepage"),
    path('',include('project_management.urls'),name="project_management"),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    path('friendship/', include('friendship.urls'),name='friendship'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'),name='reset_password'),
    path('password-reset/sent/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',success_url = reverse_lazy('reg_sign_in_out:user_login')),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html',),name='password_reset_complete'),

]

project_management/urls.py
from django.urls import path
from . import views
from project_colab import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "project_management"

urlpatterns = [
    path('project_creation/',views.project_creation,name='project_creation'),
    path('project_application/<project_id>/',views.project_application,name='project_application'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

reg_sign_in_out/urls.py
from django.urls import path
from . import views

app_name = "reg_sign_in_out"

urlpatterns = [
    path('user_login/',views.user_login,name='user_login'),
    path('registration/',views.registration,name="registration"),
    path('payment/',views.payment,name="payment"),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html > 
    <head>
        <title>Colab</title>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        {% block head_block %}
          
        {% endblock head_block %}
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;700&display=swap" rel="stylesheet">
        
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Colab</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                
                {% if request.user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'posts:home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'profilepage:profilepage'%}">Profile Page</a>
                <a class="nav-item nav-link" href="{% url 'project_management:project_creation'%}">Publish Project</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>                
                <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'networking:search' %}">
                  
                  <label for="query" >Search Type:</label>
                  <select id="query" name="d" value="{{request.GET.d}}">
                    <option>People</option>
                    <option>Project</option>
                  </select>

                  <input name="q" value="{{request.GET.q}}" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button type="submit">Search</button>
                </form>
                {%else%}

                <a class="nav-item nav-link active" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="{% url 'reg_sign_in_out:user_login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'reg_sign_in_out:registration' %}">Register</a>

                {% endif %}

                <!-- <a class="nav-item nav-link disabled" href="#">Disabled</a> -->
              </div>
            </div>
          </nav>
   
          {% block body_block %}
          
          {% endblock body_block %}

          
<script src="/static/js/jquery-3.5.1.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.waypoints.js' %}"></script>
<script src="{% static 'js/infinite.js' %}"></script>
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block head_block %}
<link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
{% endblock head_block %}

{% block body_block %}
<header>
        <h1 id="signup" >Sign Up</h1>
</header>
{% endblock %}

templates/password_reset.html
{% extends "base.html" %}
{% load static %}
{% block head_block %}
<link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
{% csrf_token %}
{% endblock head_block %}

{% block body_block %}
{% csrf_token %}
<h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Send email">
	
</form>
{% endblock %}

templates/password_reset_complete.html
{% extends "base.html" %}
{% load static %}
{% block head_block %}
<link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
{% endblock head_block %}

{% block body_block %}
<h3>Password reset complete</h3>

<p>Your password has been set. You may go ahead and log in now.</p>

{% endblock %}

templates/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% block head_block %}
<link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
{% endblock head_block %}

{% block body_block %}
{% csrf_token %}
<h3>Enter new password</h3>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Update Password">
	
</form>
{% endblock %}

templates/password_reset_sent.html
{% extends "base.html" %}
{% load static %}
{% block head_block %}
<link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
{% endblock head_block %}

{% block body_block %}

<h3>Password reset sent</h3>


<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
{% endblock %}