networking/urls.py
from django.urls import path
from . import views
from project_colab import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "networking"

urlpatterns = [
    path('search/',views.search,name='search'),
    path('profile/<username>/',views.profile,name='profile'),
    path('friend/<operation>-<usernameone>-<usernametwo>/',views.friend,name='friend'),
    path('project/projectid<project_id>/',views.project_view,name='project_view'),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

posts/urls.py
from django.urls import path
from . import views
from project_colab import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "posts"

urlpatterns = [
    path('home/',views.home,name='home'),
    path('delete-comment/<int:post_id>/',views.delete_post,name='delete_post'),
    path('delete-comment/<int:post_id>-<int:comment_id>/',views.delete_comment,name='delete_comment'),
    path('like/<int:post_id>',views.like,name='like'),
    path('dislike/<int:post_id>',views.dislike,name='dislike'),
    path('post_edit/<int:post_id>',views.editpost,name='editpost'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

project_colab/urls.py
from django.contrib import admin
from django.urls import path,include
from reg_sign_in_out import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


urlpatterns = [
    path('',views.index,name="index"),
    path('',include('reg_sign_in_out.urls'),name="reg_sign_in_out"),
    path('',include('networking.urls'),name="networking"),
    path('',include('posts.urls'),name="posts"),
    path('',include('profilepage.urls'),name="profilepage"),
    path('',include('project_management.urls'),name="project_management"),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    path('friendship/', include('friendship.urls'),name='friendship'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'),name='reset_password'),
    path('password-reset/sent/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',success_url = reverse_lazy('reg_sign_in_out:user_login')),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html',),name='password_reset_complete'),

]

project_management/urls.py
from django.urls import path
from . import views
from project_colab import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "project_management"

urlpatterns = [
    path('project_creation/',views.project_creation,name='project_creation'),
    path('project_application/<project_id>/',views.project_application,name='project_application'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

networking/models.py
from django.db import models
from django.contrib.auth.models import User

class Friends(models.Model):
    user = models.ManyToManyField(User,related_name='myfriend')
    current_user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='current_user',null=True)
    
    @classmethod
    def add_friend(cls,current_user,new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.user.add(new_friend)

    @classmethod
    def remove_friend(cls,current_user,new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.user.remove(new_friend)   


# class Chat(models.Model):
#     users = models.ForeignKey(Friends,on_delete=models.CASCADE,)
#     cha

networking/views.py
from django.shortcuts import render
from networking.models import *
from project_management.models import ProjectCreation,ProjectInductionRequest,ProjectMembers
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.db.models import Q
from project_colab import settings
from friendship.models import FriendshipRequest,Block,Follow,Friend
import os
import re

@login_required
def search(request):
    query = request.GET.get('q')
    query_type = request.GET['d']
    if query_type=="People":    
        u = User.objects.filter(Q(first_name__icontains=query) | Q(last_name__icontains=query) | Q(username__icontains=query)).exclude(username=request.user)
        return render(request,"networking/search.html",context={"user_list":u})

    elif query_type=="Project":

        word_lst = re.split('[, ]',query)
        query = Q()
        for word in word_lst:
            query = query | Q(tags__name__icontains=word) | Q(title__icontains=word)
        u = ProjectCreation.objects.filter(query).exclude(team_lead=request.user)
        return render(request,"networking/search.html",context={"project_list":u})
    

@login_required
def profile(request,username):
    u = User.objects.get(username=username)

    def check_relation(username):
        
        requested = len(FriendshipRequest.objects.filter(from_user=request.user,to_user=User.objects.get(username=username)))
        friends = len(Friend.objects.filter(from_user=request.user,to_user=User.objects.get(username=username)))
        
        if requested > 0:
            return "Requested"
        if friends > 0:
            return "Friends"
        else:
            return "None"

    related = check_relation(username)
    return render(request,"networking/profile.html",context={"user_info":u,"related":related})


@login_required
def friend(request,operation,usernameone,usernametwo):

    u1 = User.objects.get(username=usernameone)
    u2 = User.objects.get(username=usernametwo)
    
    if operation=="add":
        #Friends.add_friend(u1,u2)
        #Friends.add_friend(u2,u1)
        Friend.objects.add_friend(u1,u2)

    if operation=="remove":
        #Friends.remove_friend(u1,u2)
        #Friends.remove_friend(u2,u1)
        Friend.objects.remove_friend(u1,u2)

    if operation=="pull_request":
        FriendshipRequest.objects.get(from_user=u1,to_user=u2).delete()
    
    return HttpResponseRedirect(reverse('networking:profile',args=(usernametwo,))) 

@login_required
def project_view(request,project_id):
    info = ProjectCreation.objects.get(id=project_id)
    applied = len(ProjectInductionRequest.objects.filter(user=request.user,project__id=project_id))>0
    a_part = len(ProjectMembers.objects.filter(member=request.user,project__id=project_id))>0

    return render(request,"networking/project_details.html",context={"project_info":info,
                                                                     "applied":str(applied),
                                                                     "a_part":str(a_part)})

templates/networking/profile.html
{% extends "base.html" %}
{% block body_block %}
{% load static %}

{{user_info.first_name}}  {{user_info.last_name}} {{user_info.email}}
<img src="{{user_info_set.registration.profile_pic.url}}" alt="img" id="profileimg" onerror="this.onerror=null; this.src='/media/profile_pic/no_pro_pic.jpg'">

{% if related == "Friends" %}
    <a href="{% url 'networking:friend' 'remove' request.user.username user_info.username %}">Remove friend</a>
{% elif related == "Requested" %}    
    <a href="{% url 'networking:friend' 'pull_request' request.user.username user_info.username %}">Requested</a>
{% else%}
    <a href="{% url 'networking:friend' 'add' request.user.username user_info.username %}">Add Friend</a>
{% endif %}   

{% endblock %}

templates/networking/project_details.html
{% extends "base.html" %}
{% block body_block %}
{% load static %}

{% if project_info %}
    {{project_info.title}} <br>
    {{project_info.team_lead.first_name}}

    <a href="{{ project_info.project_file.url }}" download>Download</a>
    {% if applied == "False" and a_part == "False" %}
        <a href="{% url 'project_management:project_application' project_info.id %}">Apply</a>
    {% elif applied == "True" and a_part == "False" %}
        Applied
    {% else %}
        In
    {% endif %}
    
{% endif %}

{% endblock %}

templates/networking/search.html
{% extends "base.html" %}
{% block body_block %}
{% load static %}

{% if user_list %}
  
        {% for user in user_list %}
        <img src="{{user.registration.profile_pic.url}}" alt="img" id="profileimg" onerror="this.onerror=null; this.src='/media/profile_pic/no_pro_pic.jpg'">

                <a href="{% url 'networking:profile' user.username %}">{{user.first_name}} {{user.last_name}}</a>
                        <br>
        {% endfor %}
{% endif %}

{% if project_list %}
  
        {% for project in project_list %}
                <a href="{% url 'networking:project_view' project.id %}">{{project.title}}</a>
                <br>
        {% endfor %}
{% endif %}

{% endblock %}